export const dataset = state => state.dataset
export const nodes = state => state.nodes
export const filter = state => state.filter
export const loading = state => state.loading
export const editing = state => state.editing
export const level = state => state.level
export const legendItems = state => state.legendItems
export const viewMapping = state => state.viewMapping
export const factsheetType = state => state.factsheetType
export const maxLevel = state => state.maxLevel
export const zoom = state => state.zoom
export const maxZoom = state => state.maxZoom
export const hoverID = state => state.hoverID
